using System;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("BeeneticToolkit.Tests.Random")]

namespace BeeneticToolkit.Random {

    /// <summary>
    /// Defines the contract for random number generators that can produce values
    /// across multiple primitive types and distributions.
    /// </summary>
    public interface IRandomGenerator {

        /// <summary>
        /// Generates a random byte array with the default length.
        /// </summary>
        /// <returns>A random byte array with the default length.</returns>
        byte[] NextBytes();

        /// <summary>
        /// Generates a random byte array of the specified length.
        /// </summary>
        /// <param name="length">The number of bytes to generate.</param>
        /// <returns>A random byte array of the specified length.</returns>
        byte[] NextBytes(int length);

        /// <summary>
        /// Generates a random byte array of the specified length, with each byte
        /// falling within the specified range.
        /// </summary>
        /// <param name="length">The number of bytes to generate.</param>
        /// <param name="minInclusive">The inclusive lower bound of each generated byte.</param>
        /// <param name="maxExclusive">The exclusive upper bound of each generated byte.</param>
        /// <returns>
        /// A random byte array of the specified length, with each byte in the range
        /// [<paramref name="minInclusive"/>, <paramref name="maxExclusive"/>).
        /// </returns>
        byte[] NextBytes(int length, byte minInclusive, byte maxExclusive);

        /// <summary>
        /// Fills the provided buffer with random bytes, without allocating.
        /// </summary>
        /// <param name="buffer">The buffer to fill with random bytes.</param>
        void NextBytes(Span<byte> buffer);

        /// <summary>
        /// Generates a non-negative random integer.
        /// </summary>
        /// <returns>A non-negative random integer.</returns>
        int NextInt();

        /// <summary>
        /// Generates a non-negative random integer that is less than the specified maximum.
        /// </summary>
        /// <param name="maxExclusive">
        /// The exclusive upper bound of the random number to generate. Must be greater than 0.
        /// </param>
        /// <returns>
        /// A random integer in the range [0, <paramref name="maxExclusive"/>).
        /// </returns>
        int NextInt(int maxExclusive);

        /// <summary>
        /// Generates a random integer within the specified range.
        /// </summary>
        /// <param name="minInclusive">The inclusive lower bound of the random number to generate.</param>
        /// <param name="maxExclusive">
        /// The exclusive upper bound of the random number to generate.
        /// Must be greater than <paramref name="minInclusive"/>.
        /// </param>
        /// <returns>
        /// A random integer in the range
        /// [<paramref name="minInclusive"/>, <paramref name="maxExclusive"/>).
        /// </returns>
        int NextInt(int minInclusive, int maxExclusive);

        /// <summary>
        /// Generates a non-negative random long integer.
        /// </summary>
        /// <returns>A non-negative random long integer.</returns>
        long NextLong();

        /// <summary>
        /// Generates a non-negative random long integer that is less than the specified maximum.
        /// </summary>
        /// <param name="maxExclusive">
        /// The exclusive upper bound of the random number to generate. Must be greater than 0.
        /// </param>
        /// <returns>
        /// A random long integer in the range [0, <paramref name="maxExclusive"/>).
        /// </returns>
        long NextLong(long maxExclusive);

        /// <summary>
        /// Generates a random long integer within the specified range.
        /// </summary>
        /// <param name="minInclusive">The inclusive lower bound of the random number to generate.</param>
        /// <param name="maxExclusive">
        /// The exclusive upper bound of the random number to generate.
        /// Must be greater than <paramref name="minInclusive"/>.
        /// </param>
        /// <returns>
        /// A random long integer in the range
        /// [<paramref name="minInclusive"/>, <paramref name="maxExclusive"/>).
        /// </returns>
        long NextLong(long minInclusive, long maxExclusive);

        /// <summary>
        /// Generates a non-negative random float.
        /// </summary>
        /// <returns>A non-negative random float.</returns>
        float NextFloat();

        /// <summary>
        /// Generates a non-negative random float that is less than or equal to the specified maximum.
        /// </summary>
        /// <param name="maxInclusive">
        /// The inclusive upper bound of the random number to generate. Must be greater than 0.
        /// </param>
        /// <returns>
        /// A random float in the range [0, <paramref name="maxInclusive"/>].
        /// </returns>
        float NextFloat(float maxInclusive);

        /// <summary>
        /// Generates a random float within the specified range.
        /// </summary>
        /// <param name="minInclusive">The inclusive lower bound of the random number to generate.</param>
        /// <param name="maxInclusive">
        /// The inclusive upper bound of the random number to generate.
        /// Must be greater than <paramref name="minInclusive"/>.
        /// </param>
        /// <returns>
        /// A random float in the range
        /// [<paramref name="minInclusive"/>, <paramref name="maxInclusive"/>].
        /// </returns>
        float NextFloat(float minInclusive, float maxInclusive);

        /// <summary>
        /// Generates a non-negative random double.
        /// </summary>
        /// <returns>A non-negative random double.</returns>
        double NextDouble();

        /// <summary>
        /// Generates a non-negative random double that is less than or equal to the specified maximum.
        /// </summary>
        /// <param name="maxInclusive">
        /// The inclusive upper bound of the random number to generate. Must be greater than 0.
        /// </param>
        /// <returns>
        /// A random double in the range [0, <paramref name="maxInclusive"/>].
        /// </returns>
        double NextDouble(double maxInclusive);

        /// <summary>
        /// Generates a random double within the specified range.
        /// </summary>
        /// <param name="minInclusive">The inclusive lower bound of the random number to generate.</param>
        /// <param name="maxInclusive">
        /// The inclusive upper bound of the random number to generate.
        /// Must be greater than <paramref name="minInclusive"/>.
        /// </param>
        /// <returns>
        /// A random double in the range
        /// [<paramref name="minInclusive"/>, <paramref name="maxInclusive"/>].
        /// </returns>
        double NextDouble(double minInclusive, double maxInclusive);

        /// <summary>
        /// Generates a random double from the standard normal distribution.
        /// </summary>
        /// <returns>
        /// A normally distributed random double with mean 0.0 and standard deviation 1.0.
        /// </returns>
        double NextNormal();

        /// <summary>
        /// Generates a random double from a normal distribution with the specified mean and standard deviation.
        /// </summary>
        /// <param name="mean">The mean of the normal distribution.</param>
        /// <param name="stDev">The standard deviation of the normal distribution. Must be non-negative.</param>
        /// <returns>
        /// A normally distributed random double with the specified mean and standard deviation.
        /// </returns>
        double NextNormal(double mean, double stDev);

        /// <summary>
        /// Generates a random boolean value.
        /// </summary>
        /// <returns>A random boolean value.</returns>
        bool NextBool();

        /// <summary>
        /// Generates a random boolean value using the specified probability of returning <see langword="true"/>.
        /// </summary>
        /// <param name="probability">
        /// The probability of returning <see langword="true"/>. Must be between 0.0 and 1.0.
        /// </param>
        /// <returns>A random boolean value influenced by the specified probability.</returns>
        bool NextBool(float probability);

        /// <summary>
        /// Returns a uniformly random value of the enum type <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T">An enumeration type.</typeparam>
        /// <returns>A randomly selected value defined by <typeparamref name="T"/>.</returns>
        T NextEnum<T>() where T : struct, Enum;

        /// <summary>
        /// Returns either -1 or +1 with equal probability.
        /// </summary>
        /// <returns>-1 or +1.</returns>
        int NextSign();

        /// <summary>
        /// Generates a <see cref="Guid"/> populated with random bytes (non-cryptographic).
        /// </summary>
        /// <returns>A <see cref="Guid"/> composed of random bytes.</returns>
        Guid NextGuid();
    }
}